# docker compose file for starting a container built from the docker image itself built from the "app" module of this project
version: '3.8'
services:
  memex-service:
    image: memex-service:1.0.0
    container_name: memex-service
    environment:
      - MONGO_HOST=memex-mongo01
      - MONGO_PORT=27017
      - ELASTICSEARCH_HOST=memex-es01
      - ELASTICSEARCH_PORT=9200
      - TOKEN_ENC_KEY_SECRET=${TOKEN_ENC_KEY_SECRET}
      - USERPASS_ENC_KEY_SECRET=${USERPASS_ENC_KEY_SECRET}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - 8080:8080
    networks:
      - memex-backend

networks:
  memex-backend:
    name: memex-backend
    driver: bridge
