db:
  mongo:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
  elasticsearch:
    hostname: ${ELASTICSEARCH_HOST:localhost}
    port: ${ELASTICSEARCH_PORT:9200}

---
spring.profiles: dev
management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200/*

---
spring.profiles: prod
management:
  endpoints:
    web:
      cors:
        allowed-origins: http://matthewjohnson42.com/*
