db:
  mongo:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
  elasticsearch:
    hostname: ${ELASTICSEARCH_HOST:localhost}
    port: ${ELASTICSEARCH_PORT:9200}

security:
  oauth2:
    encKeySecret: ${TOKEN_ENC_KEY_SECRET:howMuchABulldozerCares}
  userPassword:
    encKeySecret: ${USERPASS_ENC_KEY_SECRET:absolutelyNoneAtAll}

---
spring.profiles: dev
management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:4200/*

---
spring.profiles: prod
