spring.profiles.include: enablemongorepositories,enableelasticrepositories

db:
  mongo:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
  elasticsearch:
    hostname: ${ELASTICSEARCH_HOST:localhost}
    port: ${ELASTICSEARCH_PORT:9200}

security:
  oauth2:
    encKeySecret: ${TOKEN_ENC_KEY_SECRET:howMuchABulldozerCares}
  userPassword:
    encKeySecret: ${USERPASS_ENC_KEY_SECRET:notAtAll}

cors:
  allowed-origins: "https://memex.matthewjohnson42.com, http://memex.matthewjohnson42.com, http://localhost:4200, https://localhost:4200"

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
