db:
  mongo:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
  elasticsearch:
    hostname: ${ELASTICSEARCH_HOST:localhost}
    port: ${ELASTICSEARCH_PORT:9200}

security:
  oauth2:
    encKeySecret: ${TOKEN_ENC_KEY_SECRET:howMuchABulldozerCares}
  userPassword:
    encKeySecret: ${USERPASS_ENC_KEY_SECRET:notAtAll}

---
spring.profiles: prod
cors:
  allowed-origins: "https://personal-memex-service.matthewjohnson42.com, https://memex.matthewjohnson42.com, http://localhost:8088, http://localhost:4200"
