apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memex-service
  labels:
    component: memex-service
spec:
  selector:
    matchLabels:
      component: memex-service
  serviceName: memex-service-svc
  template:
    metadata:
      name: memex-service
      labels:
        component: memex-service
    spec:
      containers:
      - name: memex-service
        image: memex-service:0.0.1
        env:
        - name: "MONGO_HOST"
          value: "${MONGO_IP}"
        - name: "MONGO_PORT"
          value: "27017"
        - name: "ELASTICSEARCH_HOST"
          value: "${ELASTICSEARCH_IP}"
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        - name: "TOKEN_ENC_KEY_SECRET"
          value: "${TOKEN_ENC_KEY_SECRET}"
        - name: "USERPASS_ENC_KEY_SECRET"
          value: "${USERPASS_ENC_KEY_SECRET}"
