# docker-compose file for starting an elasticsearch service docker container
version: '3.8'
services:
  memex-es01:
    image: memex-elastic:0.0.1
    container_name: memex-es01
    environment:
      - node.name=memex-es01
      - cluster.name=memex-es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - memex-backend

volumes:
  es01:
    driver: local

networks:
  memex-backend:
    name: memex-backend
    driver: bridge
