apiVersion: v1
kind: PersistentVolume
metadata:
  name: es01-pv
  labels:
    component: memex-es01
spec:
  capacity:
    storage: 4097M
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/es
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-26-6-83

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es01-pvc
  labels:
    component: memex-es01
spec:
  volumeName: es01-pv
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 4097M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: memex-es01
  labels:
    component: memex-es01
spec:
  selector:
    matchLabels:
      component: memex-es01
  template:
    metadata:
      labels:
        component: memex-es01
    spec:
      containers:
      - name: memex-es01
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        ports:
        - containerPort: 9200
          hostPort: 9200
        - containerPort: 9300
          hostPort: 9300
        env:
        - name: "node.name"
          value: "memex-es01"
        - name: "cluster.name"
          value: "memex-es-kube-cluster"
        - name: "discovery.type"
          value: "single-node"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: es01
      volumes:
      - name: es01
        persistentVolumeClaim:
          claimName: es01-pvc
