apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-sc
  labels:
    component: memex-elasticsearch
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  labels:
    component: memex-elasticsearch
spec:
  ports:
    - name: "9200-svc"
      port: 9200
      targetPort: 9200
    - name: "9300-svc"
      port: 9300
      targetPort: 9300
  clusterIP: ${ELASTICSEARCH_IP}
  selector:
    component: memex-elasticsearch

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    component: memex-elasticsearch
spec:
  capacity:
    storage: 4097M
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/es
  storageClassName: elasticsearch-sc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master-kube-node

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    component: memex-elasticsearch
spec:
  volumeName: elasticsearch-pv
  storageClassName: elasticsearch-sc
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 4097M
