apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  labels:
    name: elasticsearch-svc
spec:
  ports:
    - port: 9200
      targetPort: 9200
    - port: 9300
      targetPort: 9300
  clusterIP: None
#  selector:
#    role: elasticsearch

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    component: memex-elasticsearch
spec:
  capacity:
    storage: 4097M
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/es
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master-kube-node

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    component: memex-elasticsearch
spec:
  volumeName: elasticsearch-pv
  #quotes?
  storageClassName: elasticsearch-sc
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 4097M

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memex-elasticsearch
  labels:
    component: memex-elasticsearch
spec:
  selector:
    matchLabels:
      component: memex-elasticsearch
  serviceName: elasticsearch-svc
  template:
    metadata:
      labels:
        component: memex-elasticsearch
    spec:
      containers:
      - name: memex-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
#        ports:
#        - containerPort: 9200
#          hostPort: 9200
#        - containerPort: 9300
#          hostPort: 9300
        env:
        - name: "node.name"
          value: "memex-es01"
        - name: "cluster.name"
          value: "memex-es-kube-cluster"
        - name: "discovery.type"
          value: "single-node"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-volume
      volumes:
      - name: elasticsearch-volume
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
