apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
  labels:
    component: memex-mongo
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    name: memex-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: ${MONGO_IP}
  selector:
    component: memex-mongo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    component: memex-mongo
spec:
  capacity:
    storage: 4097M
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/db
  storageClassName: mongo-sc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-kube-node

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    component: memex-mongo
spec:
  volumeName: mongo-pv
  storageClassName: mongo-sc
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 4097M

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memex-mongo
  labels:
    component: memex-mongo
spec:
  selector:
    matchLabels:
      component: memex-mongo
  serviceName: mongo-svc
  template:
    metadata:
      labels:
        component: memex-mongo
    spec:
      containers:
      - name: memex-mongo
        image: memex-mongo:0.0.1
        volumeMounts:
          - mountPath: /data/db
            name: mongo-volume
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvc

---

apiVersion: batch/v1
kind: Job
metadata:
  name: memex-mongo-sidecar
spec:
  template:
    spec:
      containers:
      - name: memex-mongo-sidecar
        image: memex-mongo:0.0.1
        command: ["sh"]
        args: ["/dbInit.sh"]
        env:
        - name: "MONGO_HOST"
          value: "${MONGO_IP}"
        - name: "MONGO_DEFAULT_USER_PW"
          value: "${MONGO_DEFAULT_USER_PW}"
      restartPolicy: Never
